# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3344e8bc5d0e424b37b7c728b49204131824d34f45a322e9b11fbe0c81f6a19ae3928942953ca655d8f9d9caf4f713362dbcfa84d612269d41abc751c3a1883

test:
  secret_key_base: 591ad8be86c83d5f48683feba7ad9cf45d4899d35c5e2fe4469727183d65c38032c9e9a3d74bc8a28d5cc472f1708f159874e723e9e2f91c177559e7fa938192

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
