language: ruby

rvm:
  - 2.2.0
  - ruby-head

services:
  - mongodb

before_install:
  - cd /usr/lib/git-core/
  - sudo wget https://raw.github.com/apenwarr/git-subtree/master/git-subtree.sh
  - sudo mv git-subtree.sh git-subtree
  - sudo chmod 755 git-subtree
  - cd backend/
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs

before_script:
  - cd backend/

bundler_args: --without development

matrix:
  allow_failures:
  - rvm: ruby-head
