language: ruby

env:
  matrix:
  - DISPLAY=:99.0
  global:
  - GEEKHUB_HOME=/home/travis/build/geehub_io/geehub_io

rvm:
  - 2.2.0
  - ruby-head

services:
  - mongodb

before_install:
  - cd /usr/lib/git-core/
  - sudo wget https://raw.github.com/apenwarr/git-subtree/master/git-subtree.sh
  - sudo mv git-subtree.sh git-subtree
  - sudo chmod 755 git-subtree
  - cd $GEEKHUB_HOME/backend
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs

bundler_args: --without development

before_script:
  - cd $GEEKHUB_HOME/backend

script:
  - cd $GEEKHUB_HOME/backend && bundle exec rspec

matrix:
  allow_failures:
  - rvm: ruby-head
