language: ruby

env:
  matrix:
  - DISPLAY=:99.0
  global:
  - GEEKHUB_HOME=/home/travis/build/adham90/geekhub

rvm:
  - 2.2.0
  - ruby-head

before_install:
  - cd /usr/lib/git-core/
  - sudo wget https://raw.github.com/apenwarr/git-subtree/master/git-subtree.sh
  - sudo mv git-subtree.sh git-subtree
  - sudo chmod 755 git-subtree
  - cd $GEEKHUB_HOME/backend
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs

bundler_args: --without development

before_script:
  - cd $GEEKHUB_HOME/backend
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database geekhub_test;' -U postgres
  - bundle exec rake db:migrate

script:
  - cd $GEEKHUB_HOME/backend && bundle exec rspec

matrix:
  allow_failures:
  - rvm: ruby-head

addons:
  code_climate:
    repo_token:0c06ca5ab557d327943fe2a980fbcbdfd7ee717bedbce67edba327005a3067b0